#!/usr/bin/env bash
# Deploy Sanity Studio for Incident Copilot using Sanity CLI.
# Requires: SANITY_PROJECT_ID (and optionally SANITY_DATASET) in .env or environment.
# Run from repo root. First time: npm install -g sanity && sanity login

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
STUDIO_DIR="$ROOT_DIR/sanity-studio"

# Load .env from repo root so SANITY_PROJECT_ID and SANITY_DATASET are set
if [ -f "$ROOT_DIR/.env" ]; then
  set -a
  # shellcheck source=/dev/null
  . "$ROOT_DIR/.env"
  set +a
fi

if [ -z "${SANITY_PROJECT_ID}" ]; then
  echo "Error: SANITY_PROJECT_ID is not set. Add it to .env or export it."
  echo "  Example: echo 'SANITY_PROJECT_ID=your-project-id' >> .env"
  echo "  Create a project at https://www.sanity.io/manage or run: sanity init --create-project 'Incident Copilot'"
  exit 1
fi

export SANITY_PROJECT_ID
export SANITY_DATASET="${SANITY_DATASET:-production}"

cd "$STUDIO_DIR"
# Bake projectId/dataset into the build (Vite doesn't expose process.env to client)
echo "// Generated by scripts/sanity-deploy.sh - do not commit" > projectId.generated.ts
echo "export const projectId = '${SANITY_PROJECT_ID}';" >> projectId.generated.ts
echo "export const dataset = '${SANITY_DATASET}';" >> projectId.generated.ts
echo "Installing dependencies in sanity-studio..."
npm ci 2>/dev/null || npm install
echo "Deploying Sanity Studio (project: $SANITY_PROJECT_ID, dataset: $SANITY_DATASET)..."
npx sanity deploy --yes

echo "Done. Studio URL: https://${SANITY_PROJECT_ID}.sanity.studio"
